version: appveyor-{build}
configuration: Release
only_commits:
 message: /BUILD/
before_build:
- cmd: nuget restore
build:
  project: HTAlt.WinForms/HTAlt.WinForms.csproj
  verbosity: minimal
